version: '3'
services:
    # rabbitmq:
    #     image: rabbitmq:management
    #     restart: on-failure
    #     expose:
    #       - "5672"
    #     ports:
    #       - 5672:5672
    #       - 15672:15672
    #     networks: 
    #       - sn
    # zipkin:
    #     image: openzipkin/zipkin
    #     restart: on-failure
    #     ports:
    #     - "9411:9411"
    #     expose:
    #     - "9411"
    #     networks: 
    #     - sn
    naming-server:
        build: ./naming_server
        networks: 
        - sn
        expose:
        - 8761
        ports:
        - 8761:8761
    api-gateway-server:
        build: ./api_gateway_server
        expose:
        - 8111
        ports:
        - 8111:8111
        volumes:
        - ./api_gateway_server:/volume         
        networks: 
        - sn
        depends_on:
        - naming-server
        - zipkin
        - rabbitmq        
    person-info-service:
        build: ./PersonInfo
        expose:
        - 9000
        ports:
        - 9000:9000
        volumes:
        - ./PersonInfo:/volume         
        networks: 
        - sn
        depends_on:
        - naming-server
        - api-gateway-server
        - zipkin
        - rabbitmq
        - db           
    employee-info-service:
        build: ./employee-info-service
        expose:
        - 9500
        ports:
        - 9500:9500
        volumes:
        - ./employee-info-service:/volume         
        networks: 
        - sn
        depends_on:
        - naming-server
        - api-gateway-server
        - person-info-service
        - zipkin
        - rabbitmq
        - db
    # rest-client:
    #     build: ./rest-client
    #     expose:
    #     - 8000
    #     ports:
    #     - 8000:8000
    #     volumes:
    #     - ./rest-client:/volume
    #     networks:
    #     - sn
    #     depends_on:
    #     - naming-server
    #     - api-gateway-server
    #     - person-info-service
    #     - employee-info-service
    #     - zipkin
    #     - rabbitmq
    #     - db           
    db:
      image: mysql:8.0.18
      restart: always
      environment:
          MYSQL_DATABASE: 'db'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
      ports:
      - '3306:3306'
      expose:
      - '3306'
      volumes:
      - vc1:/var/lib/mysql
      networks:
      - sn
volumes:
    vc1:
networks:
    sn: {}